"""empty message

<<<<<<<< HEAD:migrations/versions/70a0f8f819f0_.py
Revision ID: 70a0f8f819f0
Revises: 
Create Date: 2023-02-15 18:48:22.956174
========
Revision ID: 0268222cbaa3
Revises: 
Create Date: 2023-02-16 13:11:26.267683
>>>>>>>> c0b9b86b155781f9760cc4b51ea3213f523fe54e:migrations/versions/0268222cbaa3_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/70a0f8f819f0_.py
revision = '70a0f8f819f0'
========
revision = '0268222cbaa3'
>>>>>>>> c0b9b86b155781f9760cc4b51ea3213f523fe54e:migrations/versions/0268222cbaa3_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('contacto', sa.String(length=80), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('mascotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=120), nullable=True),
    sa.Column('tamaño', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('edad', sa.String(length=80), nullable=True),
    sa.Column('raza', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.String(length=80), nullable=False),
    sa.Column('especie', sa.String(length=80), nullable=False),
    sa.Column('latitud', sa.String(length=100), nullable=True),
    sa.Column('longitud', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mascotas')
    op.drop_table('usuario')
    # ### end Alembic commands ###
