"""empty message

<<<<<<<< HEAD:migrations/versions/6f1991cb9175_.py
Revision ID: 6f1991cb9175
Revises: 
Create Date: 2023-02-22 16:47:18.658562
========
Revision ID: 61bdf97e227c
Revises: 
Create Date: 2023-02-23 18:19:37.073041
>>>>>>>> 06737f0b68374bb3c7446241f234450fcc6fc802:migrations/versions/61bdf97e227c_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/6f1991cb9175_.py
revision = '6f1991cb9175'
========
revision = '61bdf97e227c'
>>>>>>>> 06737f0b68374bb3c7446241f234450fcc6fc802:migrations/versions/61bdf97e227c_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('contacto', sa.String(length=80), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('raza', sa.String(length=80), nullable=True),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('paypal_url', sa.String(length=250), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('empresa', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('empresa'),
    sa.UniqueConstraint('username')
    )
    op.create_table('mascotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=120), nullable=True),
    sa.Column('tamaño', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.Column('edad', sa.String(length=80), nullable=True),
    sa.Column('raza', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.String(length=80), nullable=False),
    sa.Column('especie', sa.String(length=80), nullable=False),
    sa.Column('latitud', sa.String(length=100), nullable=True),
    sa.Column('longitud', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mascotas')
    op.drop_table('usuario')
    # ### end Alembic commands ###
