"""empty message

<<<<<<< HEAD:migrations/versions/f96345f9a07b_.py
<<<<<<<< HEAD:migrations/versions/ecdb1d9523d3_.py
Revision ID: ecdb1d9523d3
Revises: 
Create Date: 2023-02-07 18:31:52.480241
========
Revision ID: f96345f9a07b
Revises: 
Create Date: 2023-02-07 18:04:36.457152
>>>>>>>> ecd9271a59006a667251bf30328b3607130091e7:migrations/versions/f96345f9a07b_.py
=======
Revision ID: ab2583970324
Revises: 
Create Date: 2023-02-07 20:14:56.823127
>>>>>>> 61ae2a5277bcafc34727895e3e26cf0221e59673:migrations/versions/ab2583970324_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/f96345f9a07b_.py
<<<<<<<< HEAD:migrations/versions/ecdb1d9523d3_.py
revision = 'ecdb1d9523d3'
========
revision = 'f96345f9a07b'
>>>>>>>> ecd9271a59006a667251bf30328b3607130091e7:migrations/versions/f96345f9a07b_.py
=======
revision = 'ab2583970324'
>>>>>>> 61ae2a5277bcafc34727895e3e26cf0221e59673:migrations/versions/ab2583970324_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('contacto', sa.String(length=80), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('mascotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=120), nullable=True),
    sa.Column('tamaño', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=True),
    sa.Column('edad', sa.String(length=80), nullable=True),
    sa.Column('raza', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.String(length=80), nullable=False),
    sa.Column('especie', sa.String(length=80), nullable=False),
    sa.Column('latitud', sa.String(length=100), nullable=False),
    sa.Column('longitud', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mascotas')
    op.drop_table('usuario')
    # ### end Alembic commands ###
